# Generated by Django 6.0.2 on 2026-03-26 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('signed', 'Signed'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('error', 'Error')], default='draft', max_length=20, verbose_name='Status')),
                ('ubl_invoice_id', models.CharField(blank=True, max_length=100, verbose_name='UBL Invoice ID')),
                ('xml_content', models.TextField(blank=True, verbose_name='XML Content')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturae_b2b/xml/', verbose_name='XML File')),
                ('signed_xml_file', models.FileField(blank=True, null=True, upload_to='facturae_b2b/signed/', verbose_name='Signed XML File')),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Signature Timestamp')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('response_code', models.CharField(blank=True, max_length=50, verbose_name='Response Code')),
                ('response_message', models.TextField(blank=True, verbose_name='Response Message')),
            ],
            options={
                'verbose_name': 'E-Invoice',
                'verbose_name_plural': 'E-Invoices',
                'db_table': 'facturae_b2b_einvoice',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EInvoiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('signed', 'Signed'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('error', 'Error'), ('downloaded', 'Downloaded'), ('regenerated', 'Regenerated')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'E-Invoice Log',
                'verbose_name_plural': 'E-Invoice Logs',
                'db_table': 'facturae_b2b_log',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaeBBSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID (NIF/CIF)')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('address_province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('country_code', models.CharField(default='ES', help_text='ISO 3166-1 alpha-2 code', max_length=2, verbose_name='Country Code')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='facturae_b2b/certificates/', verbose_name='Certificate (.p12)')),
                ('certificate_password', models.CharField(blank=True, max_length=255, verbose_name='Certificate Password')),
                ('certificate_subject', models.CharField(blank=True, max_length=500, verbose_name='Certificate Subject')),
                ('certificate_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Certificate Expiry')),
                ('customization_id', models.CharField(default='urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0', max_length=255, verbose_name='Customization ID')),
                ('profile_id', models.CharField(default='urn:fdc:peppol.eu:2017:poacc:billing:01:1.0', max_length=255, verbose_name='Profile ID')),
                ('auto_generate', models.BooleanField(default=False, verbose_name='Auto-generate E-Invoice')),
                ('auto_sign', models.BooleanField(default=False, verbose_name='Auto-sign E-Invoice')),
                ('currency_code', models.CharField(default='EUR', max_length=3, verbose_name='Currency Code')),
            ],
            options={
                'verbose_name': 'E-Invoice Settings',
                'verbose_name_plural': 'E-Invoice Settings',
                'db_table': 'facturae_b2b_settings',
                'abstract': False,
            },
        ),
    ]
