# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturae_b2b', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice', to='invoicing.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='einvoicelog',
            name='einvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='facturae_b2b.einvoice', verbose_name='E-Invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='facturaebbsettings',
            unique_together={('hub_id',)},
        ),
        migrations.AddIndex(
            model_name='einvoice',
            index=models.Index(fields=['hub_id', 'status'], name='facturae_b2_hub_id_52dc38_idx'),
        ),
        migrations.AddIndex(
            model_name='einvoice',
            index=models.Index(fields=['hub_id', 'ubl_invoice_id'], name='facturae_b2_hub_id_85f52b_idx'),
        ),
    ]
